name: clsswjz_gui
description: "GUI for clsswjz-server"
publish_to: "none"
version: 1.0.2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  drift: ^2.22.1
  drift_flutter: ^0.2.3
  nanoid: ^1.0.0
  uuid: ^4.5.1
  http: ^1.2.2
  shared_preferences: ^2.3.4
  intl: ^0.20.2
  drift_db_viewer: ^2.1.0
  provider: ^6.1.2
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  mime: ^2.0.0
  file_picker: ^10.2.0
  pull_to_refresh: ^2.0.0
  json_annotation: ^4.9.0
  image_picker: ^1.0.4
  custom_refresh_indicator: ^4.0.1
  device_info_plus: ^11.2.0
  csv: ^6.0.0
  flutter_slidable: ^4.0.0
  table_calendar: ^3.0.9
  cupertino_icons: ^1.0.2
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.41
  package_info_plus: ^8.3.0
  open_filex: ^4.7.0
  flutter_quill_extensions: ^11.0.0
  flutter_quill: ^11.2.0
  photo_view: ^0.15.0
  gal: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.2
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/app_logo.png
