import '../database/dao/book_dao.dart';
import '../database/dao/note_dao.dart';
import '../database/dao/attachment_dao.dart';
import '../database/dao/log_sync_dao.dart';
import '../database/dao/category_dao.dart';
import '../database/dao/fund_dao.dart';
import '../database/dao/item_dao.dart';
import '../database/dao/shop_dao.dart';
import '../database/dao/symbol_dao.dart';
import '../database/dao/rel_book_user_dao.dart';
import '../database/dao/user_dao.dart';
import '../database/dao/debt_dao.dart';
import '../database/dao/gift_card_dao.dart';
import '../database/dao/activity_definition_dao.dart';
import '../database/dao/activity_record_dao.dart';
import '../database/dao/vehicle_dao.dart';
import '../database/dao/fuel_record_dao.dart';
import '../database/dao/item_relation_dao.dart';
import '../database/dao/user_share_dao.dart';
import '../database/dao/recurring_config_dao.dart';
import '../database/dao/bookkeeping_rule_dao.dart';
import '../database/dao/item_rel_field_dao.dart';
import 'database_manager.dart';

class DaoManager {
  static late BookDao bookDao;
  static late CategoryDao categoryDao;
  static late ItemDao itemDao;
  static late FundDao fundDao;
  static late ShopDao shopDao;
  static late SymbolDao symbolDao;
  static late RelBookUserDao relbookUserDao;
  static late LogSyncDao logSyncDao;
  static late UserDao userDao;
  static late AttachmentDao attachmentDao;
  static late NoteDao noteDao;
  static late DebtDao debtDao;
  static late GiftCardDao giftCardDao;
  static late ActivityDefinitionDao activityDefinitionDao;
  static late ActivityRecordDao activityRecordDao;
  static late VehicleDao vehicleDao;
  static late FuelRecordDao fuelRecordDao;
  static late ItemRelationDao itemRelationDao;
  static late UserShareDao userShareDao;
  static late RecurringConfigDao recurringConfigDao;
  static late BookkeepingRuleDao bookkeepingRuleDao;
  static late ItemRelFieldDao itemRelFieldDao;

  static void refreshDaos() {
    bookDao = BookDao(DatabaseManager.db);
    categoryDao = CategoryDao(DatabaseManager.db);
    itemDao = ItemDao(DatabaseManager.db);
    fundDao = FundDao(DatabaseManager.db);
    shopDao = ShopDao(DatabaseManager.db);
    symbolDao = SymbolDao(DatabaseManager.db);
    relbookUserDao = RelBookUserDao(DatabaseManager.db);
    logSyncDao = LogSyncDao(DatabaseManager.db);
    userDao = UserDao(DatabaseManager.db);
    attachmentDao = AttachmentDao(DatabaseManager.db);
    noteDao = NoteDao(DatabaseManager.db);
    debtDao = DebtDao(DatabaseManager.db);
    giftCardDao = GiftCardDao(DatabaseManager.db);
    activityDefinitionDao = ActivityDefinitionDao(DatabaseManager.db);
    activityRecordDao = ActivityRecordDao(DatabaseManager.db);
    vehicleDao = VehicleDao(DatabaseManager.db);
    fuelRecordDao = FuelRecordDao(DatabaseManager.db);
    itemRelationDao = ItemRelationDao(DatabaseManager.db);
    userShareDao = UserShareDao(DatabaseManager.db);
    recurringConfigDao = RecurringConfigDao(DatabaseManager.db);
    bookkeepingRuleDao = BookkeepingRuleDao(DatabaseManager.db);
    itemRelFieldDao = ItemRelFieldDao(DatabaseManager.db);
  }
}
